name: 'cal_dbt'
version: '1.0.0'
config-version: 2

profile: 'cal_snowflake'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cal_dbt:
    marts:
      materialized: table
    staging:
      materialized: view
